project:
  type: website
  output-dir: docs

website:
  title: "Cornelius Holler"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: Lebenslauf
      - href: projects.qmd
        text: Projekte
      - href: publications.qmd
        text: Publikationen
      - href: about.qmd
        text: Ãœber mich

format:
  html:
    theme: 
      light: lux
      dark: cyborg
    css: styles.css
    toc: true
    
editor: visual